#!/bin/bash

##
## MacOS Desktop Settings
##
## Sources:
## - https://github.com/mathiasbynens/dotfiles/blob/main/.macos
## - https://github.com/kevinSuttle/macOS-Defaults/blob/suttle/.osx
## - https://github.com/joeyhoer/starter/blob/master/system/dock.sh
##

# Basic Setup
_timestamp=$(date '+%Y%m%d%H%M')
_backup_path=${HOME}/.config/plist_backup
mkdir -p ${_backup_path}


##
## MacOS Desktop Settings 
##

# Backup global configuration
defaults read NSGlobalDomain > ${_backup_path}/NSGlobalDomain.${_timestamp}

# Regional Settings
defaults write NSGlobalDomain AppleLanguages -array  "en-US" "ar-US"
defaults write NSGlobalDomain AppleLocale -string "en_US"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Inches"
defaults write NSGlobalDomain AppleTemperatureUnit -string "Fahrenheit"
defaults write NSGlobalDomain AppleMetricUnits -bool false


# Font Smoothing
defaults write NSGlobalDomain AppleFontSmoothing -int 1

# Trackpad: enable tap to click for this user and for the login screen
defaults read com.apple.driver.AppleBluetoothMultitouch.trackpad > ${_backup_path}/com.apple.driver.AppleBluetoothMultitouch.trackpad.${_timestamp}

defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10


# Screenshots
defaults read com.apple.screencapture > ${_backup_path}/com.apple.screencapture.${_timestamp}
mkdir -p ${HOME}/Documents/Screenshots

defaults write com.apple.screencapture location -string "${HOME}/Documents/Screenshots"
defaults write com.apple.screencapture type -string "png"
defaults write com.apple.screencapture disable-shadow -bool true

# Menu Items
defaults read com.apple.systemuiserver > ${_backup_path}/com.apple.systemuiserver.${_timestamp}
defaults write com.apple.systemuiserver menuExtras -array \
"/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
"/System/Library/CoreServices/Menu Extras/Clock.menu" \
"/System/Library/CoreServices/Menu Extras/Displays.menu" \
"/System/Library/CoreServices/Menu Extras/Volume.menu"


## Finder
defaults read com.apple.finder > ${_backup_path}/com.apple.finder.${_timestamp}

# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Set the user directory as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show the ~/Library folder
chflags nohidden ~/Library && xattr -d com.apple.FinderInfo ~/Library

# Show the /Volumes folder
sudo chflags nohidden /Volumes

## Dock
defaults read com.apple.dock > ${_backup_path}/com.apple.dock.${_timestamp}

# Enable highlight hover effect for the grid view of a stack (Dock)
defaults write com.apple.dock mouse-over-hilite-stack -bool true

# Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 36

# Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Enable magnification
defaults write com.apple.dock magnification -bool true
defaults write com.apple.dock largesize -int 65

# Remove all (default) app icons from the Dock
defaults write com.apple.dock persistent-apps -array

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen
# Top left screen corner → Mission Control
defaults write com.apple.dock wvous-tl-corner -int 2
defaults write com.apple.dock wvous-tl-modifier -int 0
# Top right screen corner → Desktop
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0
# Bottom left screen corner → Start screen saver
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0



##
## Application Settings
##

# App Store
defaults read com.apple.appstore > ${_backup_path}/com.apple.appstore.${_timestamp}

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true


# Outlook
defaults read com.microsoft.Outlook > ${_backup_path}/com.microsoft.Outlook.${_timestamp}

defaults write com.microsoft.Outlook OLCalendarViewShowWeekNumberInHeaders 1
defaults write com.microsoft.Outlook MarkItemsAsReadPreferencesKey 0
defaults write com.microsoft.Outlook MessageListLeadingSwipeAction 9
defaults write com.microsoft.Outlook CalendarGridSecondTimeZoneID 8
defaults write com.microsoft.Outlook CalendarGridSecondTimeZoneLabel DUB
defaults write com.microsoft.Outlook CalendarGridShowSecondTimeZone 1
defaults write com.microsoft.Outlook CalendarGridViewTimeScale 8