#!/bin/bash

##
## MacOS Desktop Settings
##
## Sources:
## - https://github.com/mathiasbynens/dotfiles/blob/main/.macos
## - https://github.com/kevinSuttle/macOS-Defaults/blob/suttle/.osx
## - https://github.com/joeyhoer/starter/blob/master/system/dock.sh
## - https://github.com/labianchin/dotfiles/blob/master/osx/osx-for-hackers.sh
##

##
## Backup Configuration
##
_backup_path=${HOME}/.config/macos/plist_backup/$(date '+%Y%m%d%H%M')
mkdir -p ${_backup_path}

# List of pLists updated in this script
_plist=(
  /Library/Preferences/com.apple.windowserver
  com.apple.ActivityMonitor
  com.apple.commerce
  com.apple.desktopservices
  com.apple.DiskUtility
  com.apple.dock
  com.apple.driver.AppleBluetoothMultitouch.trackpad
  com.apple.finder
  com.apple.screencapture
  com.apple.SoftwareUpdate
  com.apple.swipescrolldirection
  com.apple.systemuiserver
  com.microsoft.Outlook
  NSGlobalDomain
  NSRequiresAquaSystemAppearance
)

for _p in "${_plist[@]}"; do
    echo "[Backup] ${_p}"
    _p_backup=$(echo ${_p} | sed 's,/,_,g')
    defaults read ${_p} &> ${_backup_path}/${_p_backup}
done

# Backup overall settings
defaults read > ${_backup_path}/global-settings


#####
##### MacOS Desktop Settings 
#####

##
## Dark Mode
##

osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'

##
## Regional Settings
##

defaults write NSGlobalDomain AppleLanguages -array  "en-US" "ar-US"
defaults write NSGlobalDomain AppleLocale -string "en_US"

##
## Menu Items
##

# TBD


# ##
# ## Finder
# ##

# # Finder: disable window animations and Get Info animations
# defaults write com.apple.finder DisableAllAnimations -bool true

# # Show icons for hard drives, servers, and removable media on the desktop
# defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
# defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
# defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
# defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# # Set the user directory as the default location for new Finder windows
# # For other paths, use `PfLo` and `file:///full/path/here/`
# defaults write com.apple.finder NewWindowTarget -string "PfLo"
# defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# # Finder: show all filename extensions
# defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# # Finder: show status bar
# defaults write com.apple.finder ShowStatusBar -bool true

# # Finder: show path bar
# defaults write com.apple.finder ShowPathbar -bool true

# # Enable text selection in Quick Look/Preview in Finder
# defaults write com.apple.finder QLEnableTextSelection -bool true

# # Display full POSIX path as Finder window title
# #defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# # Keep folders on top when sorting by name
# defaults write com.apple.finder _FXSortFoldersFirst -bool true

# # When performing a search, search the current folder by default
# defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# # Disable the warning when changing a file extension
# defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# # Enable spring loading for directories
# defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# # Remove the spring loading delay for directories
# defaults write NSGlobalDomain com.apple.springing.delay -float 0

# # Avoid creating .DS_Store files on network or USB volumes
# defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
# defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# # Use list view in all Finder windows by default
# # Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
# defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# # Show the ~/Library folder
# chflags nohidden ~/Library


##
## Dock
##

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# # Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Disable magnification
defaults write com.apple.dock magnification -bool false

##
## Hot corners
##

# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen

# Bottom left screen corner → Lock Screen
defaults write com.apple.dock wvous-bl-corner -int 13
defaults write com.apple.dock wvous-bl-modifier -int 0

# Bottom left screen corner → Notification Center
defaults write com.apple.dock wvous-br-corner -int 12
defaults write com.apple.dock wvous-br-modifier -int 0

# Top left screen corner → Mission Control
defaults write com.apple.dock wvous-tl-corner -int 2
defaults write com.apple.dock wvous-tl-modifier -int 0

# Top right screen corner → Desktop
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0


##
## Activity Monitor
##

# # Show the main window when launching Activity Monitor
# defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# # Visualize CPU usage in the Activity Monitor Dock icon
# defaults write com.apple.ActivityMonitor IconType -int 5

# # Show all processes in Activity Monitor
# defaults write com.apple.ActivityMonitor ShowCategory -int 0

# # Sort Activity Monitor results by CPU usage
# defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
# defaults write com.apple.ActivityMonitor SortDirection -int 0


##
## App Store
##

# Enable the automatic update check
# defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily, not just once per week
# defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
# defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
# defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Turn on app auto-update
# defaults write com.apple.commerce AutoUpdate -bool true


##
## Disk Utility
##

# Enable the debug menu in Disk Utility
# defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
# defaults write com.apple.DiskUtility advanced-image-options -bool true

##
## Backup Settings After Running the Script
##
defaults read > ${_backup_path}/global-settings-after
