# --------------------------------------------------------------------------------
# Starship Configuration File
# Sources:
#   * https://github.com/HestHub/nixos/blob/main/dotfiles/starship/starship.toml
# --------------------------------------------------------------------------------

"$schema" = 'https://starship.rs/config-schema.json'

## ------------------------------
## Prompt Configuration
## ------------------------------
add_newline = false
palette = 'nordic'

format = """
[╭ ](bold cyan_base)\
$nix_shell\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$env_var\
$custom\
$cmd_duration\
$jobs\
$os\
$container\
$shell\
$fill\
$all\
$line_break\
[╰](bold cyan_base)\
$character\
$sudo"""

[fill]
symbol = ' '

[direnv]
disabled = true

[package]
disabled = true

## ------------------------------
## Left Prompt
## ------------------------------
[character]
success_symbol = '[](bold blue2)'
error_symbol = '[](bold red_dim)'

[cmd_duration]
format = ' [ $duration](bold yellow_bright) '
show_milliseconds = true

[directory]
truncation_symbol = ''
read_only = " "
style = 'bold cyan_bright dimmed'

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold magenta_bright dimmed)'

[git_status]
format = ' ([$conflicted$untracked$renamed$modified$typechanged$deleted$staged$stashed$ahead_behind](bold magenta_bright dimmed) )'
up_to_date = ''
conflicted = '[X\($count\)](bold red_bright dimmed) '
untracked = '[?\($count\)](bold orange_bright dimmed) '
modified = '[*\($count\)](bold orange_bright dimmed) '
renamed = '[»\($count\)](bold green_bright dimmed) '
deleted = '[-\($count\)](bold red_bright dimmed) '
staged = '[+\($count\)](bold green_bright dimmed) '
stashed = '[\$\($count\)](bold yellow_bright dimmed) '

ahead = '| ↑\($count\) '
behind = '| ↓\($count\) '
diverged = '| ↕ ↑${ahead_count}↓${behind_count}'

[nix_shell]
format = '[ ](bold white0_normal)'

[status]
disabled = false
format = '[$status](bold red_base) '

[sudo]
disabled = false
format = '[ sudo: ](bold red_bright)'

## ------------------------------
## Right Prompt
## ------------------------------
[docker_context]
format = ' [ $context](bold blue1) '

[dotnet]
format = '[ ($version )](bold blue0) '
version_format = 'v${major}.${minor}'

[golang]
format = '[ $version](bold cyan_bright) '
version_format = 'v${major}.${minor}'

[gradle]
format = '[ ($version)](bold green_bright) '
version_format = 'v${major}.${minor}'

[helm]
format = '[⎈ ($version)](bold blue0) '
version_format = 'v${major}.${minor}'

[java]
format = '[ ${version}](bold red_bright) '
version_format = 'v${major}.${minor}'

[kubernetes]
disabled = false
symbol = "☸ "
format = '[$symbol$context( \($namespace\))]($style) '
style = "cyan_base bold"

[lua]
format = '[ $version](bold yellow_bright) '
version_format = 'v${major}.${minor}'

[nodejs]
format = ' [ ($version)](bold green_bright) '
version_format = 'v${major}.${minor}'

[pulumi]
format = ' [󰆦 ($username@)$stack](bold yellow_bright) '
version_format = 'v${major}.${minor}'

[python]
format = ' [ ${pyenv_prefix}(${version} )(\($virtualenv\) )](bold green_bright) '
version_format = 'v${major}.${minor}'

[rust]
format = ' [󱘗 $version](bold orange_bright) '
version_format = 'v${major}.${minor}'

[terraform]
format = ' [󰆩 $workspace](bold magenta_bright) '
version_format = 'v${major}.${minor}'

## ------------------------------
## Palette
## ------------------------------
[palettes.nordic]

# Blacks. Not in base Nord.
black0 = '#191D24'
black1 = '#1E222A'
# Slightly darker than bg.  Very useful for certain popups
black2 = '#222630'

# Grays
# This color is used on their website's dark theme.
gray0 = '#242933'
# Polar Night.
gray1 = '#2E3440'
gray2 = '#3B4252'
gray3 = '#434C5E'
gray4 = '#4C566A'

# A light blue/gray.
# From @nightfox.nvim.
gray5 = '#60728A'

# Dim white.
# default fg, has a blue tint.
white0_normal = '#BBC3D4'
# less blue tint
white0_reduce_blue = '#C0C8D8'

# Snow storm.
white1 = '#D8DEE9'
white2 = '#E5E9F0'
white3 = '#ECEFF4'

# Frost.
blue0 = '#5E81AC'
blue1 = '#81A1C1'
blue2 = '#88C0D0'

cyan_base = '#8FBCBB'
cyan_bright = '#9FC6C5'
cyan_dim = '#80B3B2'

# Aurora.
# These colors are used a lot, so we need variations for them.
# Base colors are from original Nord palette.
red_base = '#BF616A'
red_bright = '#C5727A'
red_dim = '#B74E58'

orange_base = '#D08770'
orange_bright = '#D79784'
orange_dim = '#CB775D'

yellow_base = '#EBCB8B'
yellow_bright = '#EFD49F'
yellow_dim = '#E7C173'

green_base = '#A3BE8C'
green_bright = '#B1C89D'
green_dim = '#97B67C'

magenta_base = '#B48EAD'
magenta_bright = '#BE9DB8'
magenta_dim = '#A97EA1'



#[aws]
#symbol = " "
#
#[gcloud]
#symbol = " "